'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { nanoid } from 'nanoid';
import type { Match, MatchFile, Mode, Region, SetRanks, Submode } from '@/lib/types';
import { MODES, REGIONS, SUBMODES_BY_MODE } from '@/lib/types';
import { parseTeamsBlob, parsePlayerRanks, teamsToBlob } from '@/lib/teams';
import { savedRanksFor } from '@/lib/player-ranks';
import TeamDrafter from '@/components/TeamDrafter';
import { generateRoundRobin, matchFilesToBracket, isValidTeamCount } from '@/lib/schedule';
import { formatMatchTitle } from '@/lib/match-title';
import { extractUsernames } from '@/lib/stats';

const norm = (s: string) => s.toLowerCase().trim();

type FileDraft = {
  id: string;
  label: string;
  text: string; // raw JSON text — always from a file, never hand-typed
  error: string | null;
  slot?: string; // bracket matchup this file is attached to
};

export default function MatchForm({
  existing,
  savedRanks,
}: {
  existing?: Match;
  // The admin's Set Ranks from the Player Manager, keyed mode -> sub-mode ->
  // normalized name -> rank. The autodrafter uses the entry matching this
  // tournament's mode + sub-mode, so a draft is balanced with the ranks that
  // were assigned for the exact gamemode it's for.
  savedRanks?: SetRanks;
}) {
  const router = useRouter();
  const [name, setName] = useState(existing?.name ?? '');
  const [date, setDate] = useState(existing?.date ?? '');
  const [region, setRegion] = useState<Region>(existing?.region ?? 'NA');
  const [mode, setMode] = useState<Mode>(existing?.mode ?? 'NGMC');
  const [submode, setSubmode] = useState<Submode>(existing?.submode ?? SUBMODES_BY_MODE['NGMC'][0]);
  const [teamsText, setTeamsText] = useState(
    existing ? teamsToBlob(existing.teams, existing.playerRanks) : ''
  );
  const [files, setFiles] = useState<FileDraft[]>(() =>
    existing
      ? existing.files.map((f) => ({
          id: f.id,
          label: f.label,
          text: JSON.stringify(f.data, null, 2),
          error: null,
          slot: f.slot,
        }))
      : []
  );
  // Per-file, per-team score entry: scores[fileId][normalizedTeamLabel] = "12"
  // (kept as strings while editing; parsed to numbers on submit). Seeded
  // from any scores already saved on the match.
  const [scores, setScores] = useState<Record<string, Record<string, string>>>(() => {
    const initial: Record<string, Record<string, string>> = {};
    if (existing) {
      for (const f of existing.files) {
        if (f.scores) {
          initial[f.id] = Object.fromEntries(
            Object.entries(f.scores).map(([k, v]) => [k, String(v)])
          );
        }
      }
    }
    return initial;
  });
  const [renames, setRenames] = useState<Record<string, string>>(existing?.renames ?? {});
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [teamSource, setTeamSource] = useState<'paste' | 'draft'>('paste');

  const parsedTeams = useMemo(() => parseTeamsBlob(teamsText), [teamsText]);
  // Merge over any existing ranks so re-saving without re-annotating the
  // roster doesn't silently wipe out ranks that were set previously.
  const parsedPlayerRanks = useMemo(() => {
    const fresh = parsePlayerRanks(teamsText);
    return { ...(existing?.playerRanks ?? {}), ...fresh };
  }, [teamsText, existing]);
  const rosterNames = useMemo(() => parsedTeams.flat(), [parsedTeams]);
  const rosterSetNorm = useMemo(() => new Set(rosterNames.map(norm)), [rosterNames]);
  const previewTitle = useMemo(
    () => (date && name.trim() ? formatMatchTitle(date, region, mode, submode, name) : ''),
    [date, region, mode, submode, name]
  );

  // Autogenerated fixture bracket for the current roster.
  const rounds = useMemo(() => generateRoundRobin(parsedTeams), [parsedTeams]);

  // Drafts as MatchFile-shaped objects so the shared matcher can bind them
  // to bracket slots (explicit slot first, then by detected participants).
  const filesForMatch = useMemo<MatchFile[]>(
    () =>
      files.map((f) => {
        let data: unknown = {};
        if (f.text.trim()) {
          try {
            data = JSON.parse(f.text);
          } catch {
            data = {};
          }
        }
        return { id: f.id, label: f.label, data, slot: f.slot };
      }),
    [files]
  );

  const assignment = useMemo(
    () => matchFilesToBracket(parsedTeams, filesForMatch, renames),
    [parsedTeams, filesForMatch, renames]
  );
  const draftById = useMemo(() => new Map(files.map((f) => [f.id, f])), [files]);

  // Parse every file's JSON once per render pass for the rename panel.
  const parsedFileData = useMemo(() => {
    const result: Record<string, unknown> = {};
    for (const f of files) {
      if (!f.text.trim()) continue;
      try {
        result[f.id] = JSON.parse(f.text);
      } catch {
        // Invalid JSON is surfaced separately at submit time.
      }
    }
    return result;
  }, [files]);

  // Every username, across every uploaded file, that doesn't match anyone
  // in the pasted roster. Computed from the raw JSON only (not affected by
  // renames already chosen) so an entry never disappears once you've fixed
  // it — it just shows its current mapping and stays editable.
  const unmatchedNames = useMemo(() => {
    if (rosterNames.length === 0) return [];
    const firstSeen = new Map<string, string>();
    for (const data of Object.values(parsedFileData)) {
      for (const u of extractUsernames(data)) {
        const key = norm(u);
        if (!rosterSetNorm.has(key) && !firstSeen.has(key)) firstSeen.set(key, u);
      }
    }
    return [...firstSeen.entries()]; // [normalizedKey, rawName][]
  }, [parsedFileData, rosterNames, rosterSetNorm]);

  function setRename(oldNameNorm: string, newName: string) {
    setRenames((prev) => {
      const next = { ...prev };
      if (newName) next[oldNameNorm] = newName;
      else delete next[oldNameNorm];
      return next;
    });
  }

  // Attach a JSON export to a specific matchup, replacing (and carrying
  // over any already-entered scores from) whatever was there before.
  function attachFile(slot: string, fileList: FileList | null) {
    if (!fileList || fileList.length === 0) return;
    const picked = fileList[0];
    const existingFile = assignment.bySlot[slot];
    picked.text().then((text) => {
      const newId = nanoid(6);
      setFiles((prev) => {
        const filtered = existingFile ? prev.filter((f) => f.id !== existingFile.id) : prev;
        return [
          ...filtered,
          { id: newId, label: picked.name.replace(/\.json$/i, ''), text, error: null, slot },
        ];
      });
      if (existingFile) {
        setScores((prev) => {
          const next = { ...prev };
          if (next[existingFile.id]) {
            next[newId] = next[existingFile.id];
            delete next[existingFile.id];
          }
          return next;
        });
      }
    });
  }

  function removeFile(id: string) {
    setFiles((prev) => prev.filter((f) => f.id !== id));
    setScores((prev) => {
      const next = { ...prev };
      delete next[id];
      return next;
    });
  }

  function updateFileLabel(id: string, label: string) {
    setFiles((prev) => prev.map((f) => (f.id === id ? { ...f, label } : f)));
  }

  // Entering a score for a matchup that has no file yet creates a
  // placeholder file (empty JSON) so the score has somewhere to live; the
  // JSON can be attached later and the scores carry over.
  function setScoreForSlot(slot: string, teamLabelNorm: string, value: string) {
    const existingFile = assignment.bySlot[slot];
    let fileId = existingFile?.id;
    if (!fileId) {
      fileId = nanoid(6);
      setFiles((prev) => [...prev, { id: fileId!, label: '', text: '', error: null, slot }]);
    }
    setScores((prev) => ({ ...prev, [fileId!]: { ...prev[fileId!], [teamLabelNorm]: value } }));
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setFormError(null);

    if (!date) {
      setFormError('A date is required.');
      return;
    }
    if (!name.trim()) {
      setFormError('A tournament name is required.');
      return;
    }
    if (!SUBMODES_BY_MODE[mode].includes(submode)) {
      setFormError('Pick a valid sub-mode for the selected mode.');
      return;
    }
    if (parsedTeams.length < 2) {
      setFormError('Paste at least 2 teams into the box above.');
      return;
    }
    if (!isValidTeamCount(parsedTeams.length)) {
      setFormError(`Tournaments must have exactly 4 or 6 teams (got ${parsedTeams.length}).`);
      return;
    }

    const parsedFiles: MatchFile[] = [];
    let hadFileError = false;

    // One file per bracket matchup, carrying its slot + scores.
    for (const round of rounds) {
      for (const m of round.matchups) {
        const file = assignment.bySlot[m.slot];
        const draft = file ? draftById.get(file.id) : undefined;
        const slotScores = file ? scores[file.id] : undefined;
        const parsedScores = slotScores
          ? Object.fromEntries(
              Object.entries(slotScores)
                .filter(([, v]) => v.trim() !== '' && !isNaN(Number(v)))
                .map(([k, v]) => [k, Number(v)])
            )
          : undefined;
        const hasScores = parsedScores && Object.keys(parsedScores).length > 0;
        if (!file && !hasScores) continue;
        let data: unknown = {};
        if (draft?.text.trim()) {
          try {
            data = JSON.parse(draft.text);
          } catch {
            hadFileError = true;
            continue;
          }
        }
        parsedFiles.push({
          id: file?.id ?? nanoid(6),
          label: draft?.label || `Round ${m.round}${m.cycle > 1 ? ' (reverse)' : ''}`,
          data,
          slot: m.slot,
          ...(hasScores ? { scores: parsedScores } : {}),
        });
      }
    }

    // Files that couldn't be tied to a fixture are still saved (slot-less).
    for (const f of unmatchedDrafts) {
      if (!f.text.trim()) continue;
      try {
        const data = JSON.parse(f.text);
        const fileScores = scores[f.id];
        const parsedScores = fileScores
          ? Object.fromEntries(
              Object.entries(fileScores)
                .filter(([, v]) => v.trim() !== '' && !isNaN(Number(v)))
                .map(([k, v]) => [k, Number(v)])
            )
          : undefined;
        parsedFiles.push({
          id: f.id,
          label: f.label || 'Untitled',
          data,
          ...(parsedScores && Object.keys(parsedScores).length ? { scores: parsedScores } : {}),
        });
      } catch {
        hadFileError = true;
      }
    }

    if (hadFileError) {
      setFormError('Fix the invalid JSON file(s) below.');
      return;
    }

    setSubmitting(true);
    const payload = {
      name: name.trim(),
      date,
      region,
      mode,
      submode,
      teams: parsedTeams,
      files: parsedFiles,
      renames,
      playerRanks: parsedPlayerRanks,
    };
    const res = await fetch(existing ? `/api/matches/${existing.id}` : '/api/matches', {
      method: existing ? 'PUT' : 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    setSubmitting(false);

    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      setFormError(body.error || 'Failed to save match.');
      return;
    }
    const saved = await res.json();
    router.push(`/matches/${saved.id}`);
    router.refresh();
  }

  // Unmatched drafts (files that couldn't be tied to a bracket matchup).
  const unmatchedIds = new Set(assignment.unmatched.map((f) => f.id));
  const unmatchedDrafts = files.filter((f) => unmatchedIds.has(f.id));
  const unmatchedFiles = unmatchedDrafts.filter((f) => f.text.trim());

  return (
    <form onSubmit={onSubmit} className="space-y-6">
      <div>
        <label className="mb-1 block text-xs font-medium text-textMuted">
          Tournament <span className="text-textDim">(date, region, mode, and sub-mode are mandatory)</span>
        </label>
        <div className="flex flex-wrap gap-2">
          <input
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            required
            className="rounded-md border border-border bg-surfaceAlt px-3 py-2 text-sm outline-none focus:border-textSub"
          />
          <select
            value={region}
            onChange={(e) => setRegion(e.target.value as Region)}
            required
            className="rounded-md border border-border bg-surfaceAlt px-3 py-2 text-sm outline-none focus:border-textSub"
          >
            {REGIONS.map((r) => (
              <option key={r} value={r}>
                {r}
              </option>
            ))}
          </select>
          <select
            value={mode}
            onChange={(e) => {
              const nextMode = e.target.value as Mode;
              setMode(nextMode);
              setSubmode((prev) =>
                SUBMODES_BY_MODE[nextMode].includes(prev) ? prev : SUBMODES_BY_MODE[nextMode][0]
              );
            }}
            required
            className="rounded-md border border-border bg-surfaceAlt px-3 py-2 text-sm outline-none focus:border-textSub"
          >
            {MODES.map((m) => (
              <option key={m} value={m}>
                {m}
              </option>
            ))}
          </select>
          <select
            value={submode}
            onChange={(e) => setSubmode(e.target.value)}
            required
            className="rounded-md border border-border bg-surfaceAlt px-3 py-2 text-sm outline-none focus:border-textSub"
          >
            {SUBMODES_BY_MODE[mode].map((sm) => (
              <option key={sm} value={sm}>
                {sm}
              </option>
            ))}
          </select>
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Tournament name"
            required
            className="min-w-[12rem] flex-1 rounded-md border border-border bg-surfaceAlt px-3 py-2 text-sm outline-none focus:border-textSub"
          />
        </div>
        {previewTitle && (
          <p className="mt-1.5 text-xs text-textMuted">
            Will display as: <span className="font-medium text-textSub">{previewTitle}</span>
          </p>
        )}
      </div>

        {/* Segmented source toggle — "Paste teams" (the textarea) vs "Auto-draft"
            (TeamDrafter). Only one is shown at a time; the toggle itself is
            intentionally NOT reset when switching back and forth, so a drafted
            result keeps sitting in `teamsText` even while the drafter is shown. */}
        <div className="mb-2 flex items-center gap-1.5">
          {(['paste', 'draft'] as const).map((opt) => (
            <button
              key={opt}
              type="button"
              onClick={() => setTeamSource(opt)}
              className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
                teamSource === opt
                  ? 'bg-accent text-bg'
                  : 'border border-border text-textMuted hover:border-textSub hover:text-text'
              }`}
            >
              {opt === 'paste' ? 'Paste teams' : 'Auto-draft teams'}
            </button>
          ))}
        </div>
        {teamSource === 'paste' && (
        <div>
          <label className="mb-1 block text-xs font-medium text-textMuted">
            Teams <span className="text-textDim">(paste the whole roster — score numbers are ignored)</span>
          </label>
          <textarea
          value={teamsText}
          onChange={(e) => setTeamsText(e.target.value)}
          placeholder={
            'Tommy (11) JerryTheRisu (6) hopefortomorrow (5) = 22 ivesoundfan (9) wailing (6) KappuChinooo (6) = 21 patt (11) Memories (9) carmanhan (1) = 21 Serecola (10) AJ1703 (6) Kirivert (5) = 21'
          }
          rows={4}
          className="w-full resize-y rounded-md border border-border bg-surfaceAlt px-3 py-2 font-mono text-xs outline-none focus:border-textSub"
        />
        {parsedTeams.length > 0 && !isValidTeamCount(parsedTeams.length) && (
          <p className="mt-1 text-xs text-taken">
            Tournaments must have exactly 4 or 6 teams — currently parsing {parsedTeams.length}.
          </p>
        )}
        {parsedTeams.length > 0 && (
          <div className="mt-2 flex flex-wrap gap-1.5">
            {parsedTeams.map((t, i) => (
              <span
                key={i}
                className="rounded-full border border-border bg-surfaceAlt px-2.5 py-1 text-xs text-textSub"
              >
                <span className="font-semibold text-text">Team {i + 1}:</span>{' '}
                {t
                  .map((n) => {
                    const r = parsedPlayerRanks[n.toLowerCase().trim()];
                    return r !== undefined ? `${n} (${r})` : n;
                  })
                  .join(', ')}
              </span>
            ))}
          </div>
        )}
        {teamsText.trim() && parsedTeams.length === 0 && (
          <p className="mt-1 text-xs text-taken">Couldn't parse any teams from that text.</p>
        )}
        </div>
      )}
      {teamSource === 'draft' && (
        /* Fills `teamsText` with the annotated "Name (rank) ... = total"
            format, so the ranks it used are carried into playerRanks too.
            Ranks come from the Player Manager for the mode + sub-mode picked
            above, with any pasted ranks table layered on top for overrides. */
        <TeamDrafter
          savedRanks={savedRanksFor(savedRanks ?? {}, mode, submode)}
          savedRanksLabel={`${mode} ${submode}`}
          onApply={(teams, ranks) => setTeamsText(teamsToBlob(teams, ranks))}
        />
      )}

      {rounds.length > 0 && (
        <div>
          <label className="mb-1 block text-xs font-medium text-textMuted">
            Bracket{' '}
            <span className="text-textDim">
              (attach a JSON export and enter scores for each matchup)
            </span>
          </label>
          <div className="space-y-5">
            {rounds.map((round) => (
              <div key={`${round.round}-${round.cycle}`}>
                <h3 className="mb-2 text-sm font-semibold text-text">
                  Round {round.round}
                  {round.cycle > 1 && (
                    <span className="ml-1.5 text-xs font-normal text-textDim">(reverse)</span>
                  )}
                </h3>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  {round.matchups.map((m) => {
                    const file = assignment.bySlot[m.slot];
                    const draft = file ? draftById.get(file.id) : undefined;
                    const aVal = file ? scores[file.id]?.[norm(m.labelA)] ?? '' : '';
                    const bVal = file ? scores[file.id]?.[norm(m.labelB)] ?? '' : '';
                    const aNum = aVal.trim() !== '' && !isNaN(Number(aVal)) ? Number(aVal) : null;
                    const bNum = bVal.trim() !== '' && !isNaN(Number(bVal)) ? Number(bVal) : null;
                    const aWin = aNum !== null && bNum !== null && aNum > bNum;
                    const bWin = aNum !== null && bNum !== null && bNum > aNum;
                    return (
                      <div
                        key={m.slot}
                        className="rounded-lg border border-border bg-surface px-3 py-2"
                      >
                        <div className="mb-1.5 flex items-center justify-between gap-2">
                          <span className="text-[0.65rem] uppercase tracking-wide text-textDim">
                            Match #{m.slot.replace(/^r\d+m/, '')}
                          </span>
                          {draft ? (
                            <div className="flex items-center gap-2">
                              <input
                                value={draft.label}
                                onChange={(e) => updateFileLabel(draft.id, e.target.value)}
                                placeholder="Label"
                                className="w-28 rounded border border-border bg-surfaceAlt px-1.5 py-0.5 text-xs outline-none focus:border-textSub"
                              />
                              <button
                                type="button"
                                onClick={() => removeFile(draft.id)}
                                className="text-xs text-textDim hover:text-taken"
                              >
                                Remove
                              </button>
                            </div>
                          ) : (
                            <label className="cursor-pointer text-xs text-accent hover:underline">
                              Attach JSON
                              <input
                                type="file"
                                accept=".json,application/json"
                                className="hidden"
                                onChange={(e) => {
                                  attachFile(m.slot, e.target.files);
                                  e.target.value = '';
                                }}
                              />
                            </label>
                          )}
                        </div>
                        <div className="space-y-1">
                          <AdminScoreRow
                            label={m.labelA}
                            value={aVal}
                            win={aWin}
                            onChange={(v) => setScoreForSlot(m.slot, norm(m.labelA), v)}
                          />
                          <AdminScoreRow
                            label={m.labelB}
                            value={bVal}
                            win={bWin}
                            onChange={(v) => setScoreForSlot(m.slot, norm(m.labelB), v)}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {unmatchedNames.length > 0 && (
        <div className="space-y-1.5 rounded-md border border-accent/30 bg-accent/5 p-3">
          <p className="text-xs text-accent">
            {unmatchedNames.length} name{unmatchedNames.length !== 1 ? 's' : ''} across your
            uploaded file{files.length !== 1 ? 's' : ''} don't match anyone in the pasted teams
            — rename to match, or leave as-is. You can change these any time.
          </p>
          {unmatchedNames.map(([key, rawName]) => (
            <div key={key} className="flex items-center gap-2">
              <span className="flex-shrink-0 font-mono text-xs text-textSub">{rawName}</span>
              <span className="flex-shrink-0 text-xs text-textDim">→</span>
              <select
                value={renames[key] ?? ''}
                onChange={(e) => setRename(key, e.target.value)}
                className="flex-1 rounded-md border border-border bg-surface px-2 py-1 text-xs outline-none focus:border-textSub"
              >
                <option value="">Leave as "{rawName}"</option>
                {rosterNames.map((rn) => (
                  <option key={rn} value={rn}>
                    Rename to {rn}
                  </option>
                ))}
              </select>
            </div>
          ))}
        </div>
      )}

      {unmatchedFiles.length > 0 && (
        <div className="space-y-1.5 rounded-md border border-taken/30 bg-taken/5 p-3">
          <p className="text-xs text-taken">
            {unmatchedFiles.length} file{unmatchedFiles.length !== 1 ? 's' : ''} couldn't be
            matched to a bracket matchup (their teams weren't detected). They'll still be
            saved, but won't appear in the bracket.
          </p>
          {unmatchedFiles.map((f) => (
            <div key={f.id} className="flex items-center justify-between gap-2">
              <span className="truncate font-mono text-xs text-textSub">{f.label || f.id}</span>
              <button
                type="button"
                onClick={() => removeFile(f.id)}
                className="flex-shrink-0 text-xs text-textDim hover:text-taken"
              >
                Remove
              </button>
            </div>
          ))}
        </div>
      )}

      {formError && <p className="text-sm text-taken">{formError}</p>}

      <button
        type="submit"
        disabled={submitting}
        className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg disabled:opacity-60"
      >
        {submitting ? 'Saving…' : existing ? 'Save changes' : 'Create match'}
      </button>
    </form>
  );
}

function AdminScoreRow({
  label,
  value,
  win,
  onChange,
}: {
  label: string;
  value: string;
  win: boolean;
  onChange: (v: string) => void;
}) {
  return (
    <div
      className={`flex items-center justify-between gap-2 rounded px-2 py-1 ${
        win ? 'bg-accent/10' : ''
      }`}
    >
      <span className={`truncate text-sm ${win ? 'font-semibold text-text' : 'text-textSub'}`}>
        {label}
      </span>
      <input
        type="number"
        inputMode="numeric"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder="—"
        className="w-14 rounded border border-border bg-surfaceAlt px-1.5 py-0.5 text-center text-sm outline-none focus:border-textSub"
      />
    </div>
  );
}