/**
 * Round + game selector for a tournament's computed views: a "Scope" popup
 * (see MatchStatsScope) lists the whole Stats slice's Round 1..6 checkboxes —
 * Round 1..5 for 6-team tournaments — and each bracket card below carries a
 * "Game" chip toggling that game in the stats scope, so several games (say
 * Round 5 Game 1 together with Round 6 Game 1) can be scoped at once.
 * Everything below is link-driven
 * (plain navigations to `?rounds=` / `?games=` URLs with `scroll={false}`, so
 * changing the selection keeps your place in the page), so the selection is
 * bookmarkable and needs no client state of its own.
 *
 * Scoped-down stats recompute server-side from the raw files (the raw ~2 MB
 * of JSON is never serialized into this client component), so the browser
 * only ever receives the scope definition plus the finished numbers — the
 * same precompute-and-serialize split the rest of this page uses.
 */
'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import {
  generateRoundRobin,
  type BracketFileSummary,
  type StatsScope,
} from '@/lib/schedule';
import { scopeQuery } from '@/components/MatchStatsScope';
import BracketTeamRow from '@/components/BracketTeamRow';
import type { BracketMatchup } from '@/lib/schedule';
import type { Team } from '@/lib/types';

/**
 * Autogenerated round-robin bracket, Challonge-style: every round is a
 * heading on its own line containing compact matchup cards. Rounds are
 * numbered sequentially — Round 1..6 for a double round robin (the rematch
 * leg keeps its own number, so no round repeats and no "(reverse)" tags are
 * needed), Round 1..5 for a single one — as generated by generateRoundRobin.
 * Each card lists both teams (as their full, equally-emphasized roster — no
 * leader-vs-members hierarchy) and their scores, winner highlighted. A
 * `win` / `tie` tag sits inline next to the team it applies to rather
 * than on its own line; unplayed fixtures show dashes so a freshly created
 * tournament still renders the full fixture list. Fixtures are derived
 * purely from the team list.
 *
 * Which uploaded file belongs to which fixture is worked out by the caller
 * (see summarizeBracketFiles + matchFilesToBracket in lib/schedule.ts) and
 * arrives here as `files`, keyed by slot. This component is a client
 * component, so anything passed in is serialized into the page response —
 * which is why it receives only each file's label and scores rather than the
 * raw JSON exports behind them. Hovering a team's cell highlights every cell
 * that team plays in — in every round — so one squad's whole set of games can
 * be read straight off the bracket; that hovered-team id lives here rather
 * than inside a card, because the cells it lights up are spread across all
 * the round sections below.
 */
export default function RoundRobinGrid({
  teams,
  files,
  scope,
  matchPath,
}: {
  teams: Team[];
  files: Record<string, BracketFileSummary>;
  // The stats scope shown as picked in the game chips; null hides the chips
  // entirely (the admin form's bracket, which picks files, not stats slices).
  // Chips link to `matchPath` with the sliced query string, so picking one is
  // a plain navigation — no client state to keep in sync with the tables.
  scope: StatsScope | null;
  matchPath?: string;
}) {
  const rounds = generateRoundRobin(teams);
  if (rounds.length === 0) return null;

  // Team index whose cells are highlighted right now, or null when the pointer
  // is off the bracket entirely. Cleared on the wrapper's mouseleave rather than
  // each cell's, so sliding from one cell to the next — including between two
  // cells of the same team — never blinks the highlight off in between.
  const [hoveredTeam, setHoveredTeam] = useState<number | null>(null);

  // A game chip only means something while its round isn't already keeping
  // everything: with no rounds checked the chips toggle individual games in
  // and out of the selection (any number can be picked), and a checked
  // round's chips render disabled — its games are already covered.
  const activeGames = useMemo(() => {
    if (!scope) return new Set<string>();
    if (scope.rounds.length > 0) return new Set<string>();
    return new Set(scope.games);
  }, [scope]);

  function gameHref(slot: string, displayRound: number): string {
    if (!scope || !matchPath) return matchPath ?? '';
    // Chips toggle games in and out of a game-only scope: an unchecked chip
    // adds its game to the ones already picked (any number can be checked —
    // Round 5 Game 1 together with Round 6 Game 1, say), a checked chip takes
    // it back out, and dropping the last one falls back to all stats. A chip
    // on a checked round isn't a toggle — those games are already kept — so
    // it points at the plain round view instead (it renders disabled anyway).
    let next: StatsScope;
    if (scope.rounds.includes(displayRound)) {
      next = { rounds: [displayRound], games: [] };
    } else if (scope.games.includes(slot)) {
      next = { rounds: [], games: scope.games.filter((s) => s !== slot) };
    } else {
      next = { rounds: [], games: [...scope.games, slot] };
    }
    return `${matchPath}${scopeQuery(next)}`;
  }

  return (
    <div className="space-y-3" onMouseLeave={() => setHoveredTeam(null)}>
      {rounds.map((round) => (
        <div key={round.displayRound}>
          <h3 className="mb-1 text-xs font-semibold uppercase tracking-wide text-textMuted">
            Round {round.displayRound}
          </h3>
          <div className="grid grid-cols-1 gap-1.5 sm:grid-cols-2">
            {round.matchups.map((m, i) => (
              <MatchupCard
                key={m.slot}
                matchup={m}
                gameNumber={i + 1}
                teamA={teams[m.teamAIndex]}
                teamB={teams[m.teamBIndex]}
                file={files[m.slot]}
                hoveredTeam={hoveredTeam}
                onHoverTeam={setHoveredTeam}
                gameSelected={scope !== null && activeGames.has(m.slot)}
                gameTitle={
                  scope !== null && activeGames.has(m.slot)
                    ? 'Remove this game from the stats scope'
                    : scope !== null && scope.games.length > 0
                      ? 'Add this game to the stats scope'
                      : 'Scope stats to this game'
                }
                gameDisabled={
                  scope === null ||
                  !matchPath ||
                  (scope.rounds.length > 0 && scope.rounds.includes(m.displayRound))
                }
                gameHref={gameHref(m.slot, m.displayRound)}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function MatchupCard({
  matchup,
  gameNumber,
  teamA,
  teamB,
  file,
  hoveredTeam,
  onHoverTeam,
  gameSelected,
  gameTitle,
  gameDisabled,
  gameHref,
}: {
  matchup: BracketMatchup;
  gameNumber: number;
  teamA: Team;
  teamB: Team;
  file?: BracketFileSummary;
  hoveredTeam: number | null;
  onHoverTeam: (teamIndex: number) => void;
  // Game-level stats-scope chip: links to the sliced URL when enabled.
  // Missing entirely on read-only bracket renders — the admin form drives
  // its own attach-file flow through these cards, not a stats scope. A
  // disabled chip means the game is already kept by its checked round, so
  // linking anywhere would change nothing.
  gameSelected?: boolean;
  // Hover title for the chip: adding to an existing game selection is worded
  // differently from scoping to a first one.
  gameTitle?: string;
  gameDisabled?: boolean;
  gameHref?: string;
}) {
  const scores = file?.scores;
  const aScore = scores?.[matchup.labelA.toLowerCase().trim()];
  const bScore = scores?.[matchup.labelB.toLowerCase().trim()];
  const bothScored = aScore !== undefined && bScore !== undefined;
  const aWin = bothScored && aScore > bScore;
  const bWin = bothScored && bScore > aScore;
  const tie = bothScored && aScore === bScore;

  return (
    <div
      className={`rounded-md border px-2 py-1 ${
        bothScored ? 'border-border bg-surface' : 'border-dashed border-border bg-surface/40'
      }`}
    >
      <div className="flex items-center justify-between gap-2">
        <span className="text-[0.6rem] uppercase tracking-wide text-textDim">
          Round {matchup.displayRound} · Game {gameNumber}
        </span>
        {gameHref && !gameDisabled && (
          <Link
            href={gameHref}
            scroll={false}
            title={
              gameTitle ??
              (gameSelected ? 'Remove this game from the stats scope' : 'Scope stats to this game')
            }
            className={`rounded-full px-2 py-0.5 text-[0.6rem] font-medium transition-colors ${
              gameSelected
                ? 'bg-accent text-bg'
                : 'border border-border text-textMuted hover:border-textSub hover:text-text'
            }`}
          >
            {gameSelected ? '✓ Game' : 'Game'}
          </Link>
        )}
      </div>
      <Row
        members={teamA}
        teamIndex={matchup.teamAIndex}
        score={aScore}
        result={tie ? 'tie' : aWin ? 'win' : null}
        highlighted={hoveredTeam === matchup.teamAIndex}
        onHover={onHoverTeam}
      />
      <Row
        members={teamB}
        teamIndex={matchup.teamBIndex}
        score={bScore}
        result={tie ? 'tie' : bWin ? 'win' : null}
        highlighted={hoveredTeam === matchup.teamBIndex}
        onHover={onHoverTeam}
      />
    </div>
  );
}

// One team of a matchup, rendered through the shared bracket row (see
// components/BracketTeamRow.tsx — same roster chips, team colors, hover
// highlight and win/tie tag as the admin form's bracket) with this view's
// read-only score pill passed in as the right-hand control.
function Row({
  members,
  teamIndex,
  score,
  result,
  highlighted,
  onHover,
}: {
  members: Team;
  teamIndex: number;
  score?: number;
  result: 'win' | 'tie' | null;
  highlighted: boolean;
  onHover: (teamIndex: number) => void;
}) {
  const win = result === 'win';
  const tie = result === 'tie';
  return (
    <BracketTeamRow
      members={members}
      teamIndex={teamIndex}
      result={result}
      highlighted={highlighted}
      onHover={onHover}
      score={
        <span
          className={`flex-shrink-0 rounded px-1.5 text-xs font-semibold ${
            win
              ? 'bg-accent text-bg'
              : tie
                ? 'bg-surfaceAlt text-text'
                : score === undefined
                  ? 'text-textDim'
                  : 'text-textMuted'
          }`}
        >
          {score === undefined ? '–' : score}
        </span>
      }
    />
  );
}