'use client';

import { useState } from 'react';
import { generateRoundRobin, matchFilesToBracket, type BracketMatchup } from '@/lib/schedule';
import BracketTeamRow from '@/components/BracketTeamRow';
import type { Match, Team } from '@/lib/types';

/**
 * Autogenerated round-robin bracket, Challonge-style: every round is a
 * heading on its own line containing compact matchup cards, with each
 * round's reversed rematch leg following it immediately (R1, R1
 * reverse, R2, R2 reverse, ...) as generated by generateRoundRobin. Each
 * card lists both teams (as their full, equally-emphasized roster — no
 * leader-vs-members hierarchy) and their scores, winner highlighted. A
 * `win` / `tie` tag sits inline next to the team it applies to rather
 * than on its own line; unplayed fixtures show dashes so a freshly created
 * tournament still renders the full fixture list. Fixtures are derived
 * purely from the team list, and an uploaded file (if any) is attached to
 * its matchup by slot or by the two teams detected in it. Hovering a team's
 * cell highlights every cell that team plays in — in every round — so one
 * squad's whole set of games can be read straight off the bracket; that
 * hovered-team id lives here rather than inside a card, because the cells it
 * lights up are spread across all the round sections below.
 */
export default function RoundRobinGrid({
  match,
}: {
  match: Pick<Match, 'teams' | 'files' | 'renames'>;
}) {
  const teams = match.teams;
  const rounds = generateRoundRobin(teams);
  if (rounds.length === 0) return null;

  const { bySlot } = matchFilesToBracket(teams, match.files, match.renames ?? {});

  // Team index whose cells are highlighted right now, or null when the pointer
  // is off the bracket entirely. Cleared on the wrapper's mouseleave rather than
  // each cell's, so sliding from one cell to the next — including between two
  // cells of the same team — never blinks the highlight off in between.
  const [hoveredTeam, setHoveredTeam] = useState<number | null>(null);

  return (
    <div className="space-y-3" onMouseLeave={() => setHoveredTeam(null)}>
      {rounds.map((round) => (
        <div key={`${round.round}-${round.cycle}`}>
          <h3 className="mb-1 text-xs font-semibold uppercase tracking-wide text-textMuted">
            Round {round.round}
            {round.cycle > 1 && (
              <span className="ml-1.5 font-normal normal-case text-textDim">(reverse)</span>
            )}
          </h3>
          <div className="grid grid-cols-1 gap-1.5 sm:grid-cols-2">
            {round.matchups.map((m) => (
              <MatchupCard
                key={m.slot}
                matchup={m}
                teamA={teams[m.teamAIndex]}
                teamB={teams[m.teamBIndex]}
                file={bySlot[m.slot]}
                hoveredTeam={hoveredTeam}
                onHoverTeam={setHoveredTeam}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function MatchupCard({
  matchup,
  teamA,
  teamB,
  file,
  hoveredTeam,
  onHoverTeam,
}: {
  matchup: BracketMatchup;
  teamA: Team;
  teamB: Team;
  file?: Match['files'][number];
  hoveredTeam: number | null;
  onHoverTeam: (teamIndex: number) => void;
}) {
  const scores = file?.scores;
  const aScore = scores?.[matchup.labelA.toLowerCase().trim()];
  const bScore = scores?.[matchup.labelB.toLowerCase().trim()];
  const bothScored = aScore !== undefined && bScore !== undefined;
  const aWin = bothScored && aScore > bScore;
  const bWin = bothScored && bScore > aScore;
  const tie = bothScored && aScore === bScore;

  return (
    <div
      className={`rounded-md border px-2 py-1 ${
        bothScored ? 'border-border bg-surface' : 'border-dashed border-border bg-surface/40'
      }`}
    >
      <Row
        members={teamA}
        teamIndex={matchup.teamAIndex}
        score={aScore}
        result={tie ? 'tie' : aWin ? 'win' : null}
        highlighted={hoveredTeam === matchup.teamAIndex}
        onHover={onHoverTeam}
      />
      <Row
        members={teamB}
        teamIndex={matchup.teamBIndex}
        score={bScore}
        result={tie ? 'tie' : bWin ? 'win' : null}
        highlighted={hoveredTeam === matchup.teamBIndex}
        onHover={onHoverTeam}
      />
    </div>
  );
}

// One team of a matchup, rendered through the shared bracket row (see
// components/BracketTeamRow.tsx — same roster chips, team colors, hover
// highlight and win/tie tag as the admin form's bracket) with this view's
// read-only score pill passed in as the right-hand control.
function Row({
  members,
  teamIndex,
  score,
  result,
  highlighted,
  onHover,
}: {
  members: Team;
  teamIndex: number;
  score?: number;
  result: 'win' | 'tie' | null;
  highlighted: boolean;
  onHover: (teamIndex: number) => void;
}) {
  const win = result === 'win';
  const tie = result === 'tie';
  return (
    <BracketTeamRow
      members={members}
      teamIndex={teamIndex}
      result={result}
      highlighted={highlighted}
      onHover={onHover}
      score={
        <span
          className={`flex-shrink-0 rounded px-1.5 text-xs font-semibold ${
            win
              ? 'bg-accent text-bg'
              : tie
                ? 'bg-surfaceAlt text-text'
                : score === undefined
                  ? 'text-textDim'
                  : 'text-textMuted'
          }`}
        >
          {score === undefined ? '–' : score}
        </span>
      }
    />
  );
}