import { computeGameResult } from './results';
import { extractUsernames, norm } from './stats';
import type { Match, MatchFile, Team } from './types';

// The only two valid tournament sizes. Cycle count is derived from team
// count, never chosen separately — 4 teams always double round robin
// (every pair plays twice, 6 games per team), 6 teams always single round
// robin (every pair plays once, 5 games per team).
export const VALID_TEAM_COUNTS = [4, 6] as const;

export function roundRobinCycles(teamCount: number): number {
  if (teamCount === 4) return 2;
  if (teamCount === 6) return 1;
  // Shouldn't happen if the 4/6 constraint is enforced at save time, but
  // fall back to single round robin rather than throwing mid-render.
  return 1;
}

export function gamesPerTeam(teamCount: number): number {
  return (teamCount - 1) * roundRobinCycles(teamCount);
}

export function totalGamesExpected(teamCount: number): number {
  return (teamCount * gamesPerTeam(teamCount)) / 2;
}

export interface FixturePairProgress {
  teamAIndex: number;
  teamBIndex: number;
  labelA: string;
  labelB: string;
  needed: number; // = cycles
  played: number; // games actually recorded between this exact pair
  remaining: number;
}

export interface ScheduleProgress {
  cycles: number;
  gamesPerTeam: number;
  totalExpected: number;
  totalRecorded: number;
  pairs: FixturePairProgress[];
  missingPairs: FixturePairProgress[]; // pairs with remaining > 0
  complete: boolean;
}

/**
 * Cross-references the expected round-robin fixture list (every pair,
 * `cycles` times) against however many games are actually recorded for
 * each pair, so the admin can see what's left to upload. Doesn't care
 * which specific two games satisfy a 2x pairing — just the count.
 */
export function computeScheduleProgress(match: Pick<Match, 'teams' | 'files'>): ScheduleProgress {
  const teams = match.teams;
  const n = teams.length;
  const cycles = roundRobinCycles(n);

  // Count recorded games per pair by scanning every scored file.
  const playedCount = new Map<string, number>();
  for (const file of match.files) {
    const result = computeGameResult(file, teams);
    if (!result || result.entries.length !== 2) continue;
    const [i, j] = result.entries.map((e) => e.teamIndex).sort((a, b) => a - b);
    const key = `${i},${j}`;
    playedCount.set(key, (playedCount.get(key) ?? 0) + 1);
  }

  const pairs: FixturePairProgress[] = [];
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const played = playedCount.get(`${i},${j}`) ?? 0;
      pairs.push({
        teamAIndex: i,
        teamBIndex: j,
        labelA: teams[i][0],
        labelB: teams[j][0],
        needed: cycles,
        played,
        remaining: Math.max(0, cycles - played),
      });
    }
  }

  const totalRecorded = pairs.reduce((s, p) => s + Math.min(p.played, p.needed), 0);
  const totalExpected = totalGamesExpected(n);

  return {
    cycles,
    gamesPerTeam: gamesPerTeam(n),
    totalExpected,
    totalRecorded,
    pairs,
    missingPairs: pairs.filter((p) => p.remaining > 0),
    complete: pairs.every((p) => p.remaining === 0),
  };
}

export function isValidTeamCount(n: number): boolean {
  return (VALID_TEAM_COUNTS as readonly number[]).includes(n);
}

// ---- autogenerated bracket -------------------------------------------------

export interface BracketMatchup {
  slot: string; // opaque stable key, e.g. "r1m0" = fixture, match 0. The
  //              number is the fixture's position in the legacy
  //              cycle-major sequence, NOT the round number shown on
  //              screen — see generateRoundRobin. Never derive it from
  //              display order: it is persisted on saved files.
  displayRound: number; // 1-based sequential round shown on screen — Round
  //              1..6 for a double round robin (Round 1..5 for 6 teams).
  //              Unlike `round` it never repeats, so it is what round
  //              headings, file labels and the stats scope use.
  round: number; // 1-based round within a single round-robin pass. The
  //                reverse leg repeats the same numbers, so displayRound
  //                2 is round 1's rematch, 4 is round 2's, 6 is round 3's.
  cycle: number; // 1-based round-robin cycle this round belongs to
  teamAIndex: number;
  teamBIndex: number;
  labelA: string;
  labelB: string;
}

export interface BracketRound {
  displayRound: number; // sequential round number shown on screen (1..6)
  round: number; // round number within its cycle (repeats on the reverse leg)
  cycle: number; // 1-based cycle this leg belongs to, so round + cycle is unique
  matchups: BracketMatchup[];
}

export function bracketSlot(round: number, index: number): string {
  return `r${round}m${index}`;
}

/**
 * One single round-robin pass using the circle method: team 0 is pinned
 * and the rest rotate, producing `n - 1` rounds of `n / 2` pairings.
 * Returns raw index pairs per round.
 */
function singleRoundRobinPairs(n: number): [number, number][][] {
  const rot: number[] = [];
  for (let i = 1; i < n; i++) rot.push(i);
  const rounds: [number, number][][] = [];
  for (let r = 0; r < n - 1; r++) {
    const pairs: [number, number][] = [[0, rot[rot.length - 1]]];
    for (let k = 0; k < (n - 2) / 2; k++) {
      pairs.push([rot[k], rot[rot.length - 2 - k]]);
    }
    rounds.push(pairs);
    rot.unshift(rot.pop() as number); // rotate clockwise
  }
  return rounds;
}

/**
 * Builds the full fixture bracket for a tournament: every round with its
 * matchups, autogenerated from the team list. 4 teams produce a double
 * round robin (2 cycles, 6 legs), 6 teams a single one (5 rounds). The
 * second cycle flips each pairing's side, and each of its legs is emitted
 * directly after the round it mirrors — R1, R1 (reverse), R2, R2
 * (reverse), ... — rather than appending the whole reversed cycle at the
 * end, so a round and its rematch read as one block.
 *
 * Every matchup carries a stable `slot` key so an uploaded JSON file (and
 * its scores) can be attached to a specific fixture. Slots keep the
 * cycle-major numbering they have always had (cycle * roundsPerCycle +
 * round); they are persisted on saved files, so they must not be
 * renumbered to follow the display order above.
 */
export function generateRoundRobin(teams: Team[]): BracketRound[] {
  const n = teams.length;
  if (!isValidTeamCount(n)) return [];
  const cycles = roundRobinCycles(n);
  const base = singleRoundRobinPairs(n);
  const roundsPerCycle = base.length;
  const rounds: BracketRound[] = [];
  let displayRound = 0;
  for (let r = 0; r < roundsPerCycle; r++) {
    for (let c = 0; c < cycles; c++) {
      displayRound++;
      const matchups: BracketMatchup[] = base[r].map(([a, b], i) => {
        const [x, y] = c === 1 ? [b, a] : [a, b];
        return {
          slot: bracketSlot(c * roundsPerCycle + r + 1, i),
          displayRound,
          round: r + 1,
          cycle: c + 1,
          teamAIndex: x,
          teamBIndex: y,
          labelA: teams[x][0],
          labelB: teams[y][0],
        };
      });
      rounds.push({ displayRound, round: r + 1, cycle: c + 1, matchups });
    }
  }
  return rounds;
}

/** Roster team indices whose players appear in a raw song-history file. */
export function fileParticipantIndices(
  file: Pick<MatchFile, 'data'>,
  teams: Team[],
  renames: Record<string, string> = {}
): number[] {
  const normTeams = teams.map((t) => t.map(norm));
  const present = new Set<string>();
  for (const u of extractUsernames(file.data)) {
    present.add(norm(renames[norm(u)] || u));
  }
  const idx: number[] = [];
  normTeams.forEach((t, i) => {
    if (t.some((p) => present.has(p))) idx.push(i);
  });
  return idx;
}

/**
 * The play timestamp the game writes into its own export name —
 * `EMQ_SongHistory_2026-09-27T01_52_55` → `2026-09-27T01_52_55`. Every
 * component is fixed width, so comparing the strings is already a
 * chronological comparison. Files renamed to something without one
 * (or hand-labelled at save time) get null.
 */
export function exportTimestamp(label: string): string | null {
  const m = label.match(/\d{4}-\d{2}-\d{2}T\d{2}[_:]\d{2}[_:]\d{2}/);
  return m ? m[0] : null;
}

/**
 * Orders two exports by the time in their names, earliest first. This is the
 * order pass 2 of matchFilesToBracket tries them in, so when a pair has two
 * recorded games the earlier one lands on the pair's first fixture and the
 * later one on its rematch. Files with no parseable timestamp sort after the
 * timed ones and keep their relative order (sort is stable).
 */
function compareByExportTime(a: string, b: string): number {
  const ta = exportTimestamp(a);
  const tb = exportTimestamp(b);
  if (ta === null && tb === null) return 0;
  if (ta === null) return 1;
  if (tb === null) return -1;
  return ta < tb ? -1 : ta > tb ? 1 : 0;
}

export interface BracketAssignment {
  bySlot: Record<string, MatchFile>; // matchup slot -> attached file
  unmatched: MatchFile[]; // files that couldn't be tied to a fixture
}

/**
 * Binds uploaded files to bracket matchups. Files carrying an explicit
 * `slot` win outright; the rest are matched by the two teams detected in
 * them (first empty slot for that pair, tried in export-time order so a
 * pair's earlier game lands on its first fixture — see compareByExportTime).
 * Anything left over is returned as `unmatched` so it isn't silently dropped.
 */
export function matchFilesToBracket(
  teams: Team[],
  files: MatchFile[],
  renames: Record<string, string> = {}
): BracketAssignment {
  const rounds = generateRoundRobin(teams);
  // Pair key -> slots in bracket order (2 for a double round robin).
  const slotsByPair = new Map<string, string[]>();
  const allSlots: string[] = [];
  for (const rr of rounds) {
    for (const m of rr.matchups) {
      const key = `${Math.min(m.teamAIndex, m.teamBIndex)},${Math.max(m.teamAIndex, m.teamBIndex)}`;
      (slotsByPair.get(key) ?? slotsByPair.set(key, []).get(key)!).push(m.slot);
      allSlots.push(m.slot);
    }
  }

  const bySlot: Record<string, MatchFile> = {};
  const used = new Set<string>();
  const remaining: MatchFile[] = [];

  // Pass 1: explicit slots.
  for (const file of files) {
    if (file.slot && allSlots.includes(file.slot) && !bySlot[file.slot]) {
      bySlot[file.slot] = file;
      used.add(file.id);
    } else {
      remaining.push(file);
    }
  }

  // Pass 2: infer by the two teams present in each file. A pair that played
  // twice (double round robin) yields the same two teams in both files, so
  // the try order decides which leg each lands on: sort by the play time the
  // game writes into the export's own name (EMQ_SongHistory_2026-09-27T01_52_55)
  // — the earlier game first, so it fills the pair's first fixture and the
  // later one its rematch.
  for (const file of [...remaining].sort((a, b) => compareByExportTime(a.label, b.label))) {
    const idx = fileParticipantIndices(file, teams, renames);
    if (idx.length !== 2) continue;
    const key = `${Math.min(idx[0], idx[1])},${Math.max(idx[0], idx[1])}`;
    const slot = (slotsByPair.get(key) ?? []).find((s) => !bySlot[s]);
    if (slot) {
      bySlot[slot] = file;
      used.add(file.id);
    }
  }

  return { bySlot, unmatched: files.filter((f) => !used.has(f.id)) };
}

/**
 * What a bracket card actually renders out of an attached file: which two
 * teams scored what. `data` (the raw EMQ export, ~100 kB each) is
 * deliberately left behind.
 *
 * RoundRobinGrid is a client component, so anything handed to it is
 * serialized into the page response as well as the props — passing whole
 * files would ship every tournament's raw JSON to the browser, which is
 * what this shape exists to avoid. Slots with no attached file are simply
 * absent, and cards for them render as unplayed.
 */
export interface StatsScope {
  // Which displayed rounds are in scope (1-based `displayRound`). Empty =
  // every round.
  rounds: number[];
  // Individually-checked games, as bracket `slot` keys, on top of whatever
  // `rounds` covers. Empty = no single-game picks.
  games: string[];
}

/** True when the scope keeps nothing out — the whole tournament's stats. */
export function isFullScope(scope: StatsScope): boolean {
  return scope.rounds.length === 0 && scope.games.length === 0;
}

/**
 * Which of `match.files` fall inside `scope`, in the match's own file order.
 * Files are resolved to bracket fixtures exactly the way the bracket (and the
 * admin form) attaches them — explicit `slot` first, otherwise the two teams
 * detected in the file — so the stats slice agrees with the fixtures the
 * selector's round/game chips were built from. Files that can't be placed on
 * the bracket only count inside the full scope.
 */
export function filesInStatsScope(
  teams: Team[],
  files: MatchFile[],
  renames: Record<string, string>,
  scope: StatsScope
): MatchFile[] {
  if (isFullScope(scope)) return files;
  const assignment = matchFilesToBracket(teams, files, renames);
  const slotToRound = new Map<string, number>();
  for (const matchups of generateRoundRobin(teams).map((r) => r.matchups)) {
    for (const m of matchups) slotToRound.set(m.slot, m.displayRound);
  }
  const roundSet = new Set(scope.rounds);
  const gameSet = new Set(scope.games);
  const kept: MatchFile[] = [];
  for (const file of files) {
    const entry = Object.entries(assignment.bySlot).find(([, f]) => f.id === file.id);
    if (!entry) continue; // unmatched files have no round/game — full scope only
    const [slot] = entry;
    if (gameSet.has(slot)) {
      kept.push(file);
      continue;
    }
    const displayRound = slotToRound.get(slot);
    if (displayRound !== undefined && roundSet.has(displayRound)) kept.push(file);
  }
  return kept;
}

export interface BracketFileSummary {
  label: string;
  scores?: Record<string, number>;
}

export function summarizeBracketFiles(
  assignment: BracketAssignment
): Record<string, BracketFileSummary> {
  const summarized: Record<string, BracketFileSummary> = {};
  for (const [slot, file] of Object.entries(assignment.bySlot)) {
    summarized[slot] = { label: file.label, scores: file.scores };
  }
  return summarized;
}
