// A team is just an ordered list of usernames. The first name is used
// as the team's display label everywhere in the UI (e.g. "karira's team").
export type Team = string[];

export type Region = 'NA' | 'EU' | 'Asia';
export const REGIONS: Region[] = ['NA', 'EU', 'Asia'];

/**
 * Same-day tour order: NA first, then EU, then Asia — the order the regions
 * play in on a shared date. Used as the tiebreak between `date` and
 * `created_at` everywhere tournaments are listed (see `MATCH_ORDER_BY`).
 * Unknown/legacy region values sort last so they never wedge between the
 * known three.
 */
export const REGION_ORDER: Record<string, number> = { NA: 0, EU: 1, Asia: 2 };

export function regionOrder(region: string): number {
  return REGION_ORDER[region] ?? 3;
}

// Gamemodes in priority order: Erumode is listed first everywhere modes are
// offered or displayed — the match form's picker, the tournament-list chips,
// the /players sub-mode rows, per-mode stat sections, the Player Manager's
// default selection, ...
export type Mode = 'NGMC' | 'Erumode';
export const MODES: Mode[] = ['Erumode', 'NGMC'];

// Sub-mode options depend on the tournament's mode.
export const SUBMODES_BY_MODE: Record<Mode, string[]> = {
  NGMC: ['Normal', 'Random'],
  Erumode: ['Normal', 'Random', 'Balanced', 'No Vocal'],
};
export type Submode = string;

// One uploaded/pasted EMQ song-history JSON export. `data` is the raw
// parsed JSON blob exactly as exported from the game (structure is
// intentionally loose here — see lib/stats.ts for the fields we read).
export interface MatchFile {
  id: string;
  label: string;
  data: unknown;
  // Which autogenerated bracket matchup this file belongs to, as a stable
  // slot key (e.g. "r1m0" = round 1, match 0). Optional: files uploaded
  // before slots existed (or via a plain batch) are matched to a slot by
  // their detected participants instead.
  slot?: string;
  // Score each participating team got in this game, keyed by the team's
  // normalized label (norm() of team[0], the team's first/identifying
  // player) — stable across roster edits, unlike a positional index.
  // Optional: a file doesn't need a score entered for stats to still work,
  // it just won't contribute to the Results ranking until it does.
  scores?: Record<string, number>;
}

export interface Match {
  id: string;
  // Composed as "{date} {region} {mode} {submode} {name}", e.g.
  // "2026/12/31 NA NGMC Normal Winter Cup".
  title: string;
  name: string; // free-text tournament name the admin typed
  date: string; // YYYY-MM-DD, mandatory
  region: Region;
  mode: Mode;
  submode: Submode;
  createdAt: string; // ISO timestamp
  teams: Team[];
  files: MatchFile[];
  // Player-name reconciliation: norm(oldName from JSON) -> newName (roster
  // name). Kept as its own field — never baked into `files` — so a rename
  // stays visible and editable in the admin form on every future edit,
  // instead of disappearing once applied.
  renames: Record<string, string>;
  // Substitute reconciliation: norm(name from JSON) -> norm(roster player
  // they stood in for). The counterpart to `renames`, chosen when the odd
  // name out in an upload is a *different person* filling a roster slot
  // rather than the roster player under a new name — see
  // lib/substitutes.ts. A sub keeps its own identity in every aggregate
  // (its stats are never merged into the replaced player's), but counts as
  // part of the replaced player's team for fixture placement, attack
  // attribution and synergy. Same rules as `renames`: its own field, keyed
  // normalized, editable for as long as the match exists.
  substitutes: Record<string, string>;
  // Each player's individual rank number, parsed from "(N)" next to their
  // name in the pasted roster — keyed by normalized username. Separate
  // from Tier (a player's ordinal position within their team), which is
  // derived from `teams` order and never stored.
  playerRanks: Record<string, number>;
  // Tournament stays visible (lists, its own page, exports) but contributes
  // to no player aggregates — last-5 nor all-time. See lib/store.ts
  // `statsMatches` for the single filter every derivation goes through.
  excludeFromStats: boolean;
}

/**
 * A match without its raw file payloads, for the list views that only need
 * the roster and a file *count*. `files` is by far the heaviest column (one
 * raw EMQ export is ~100 kB, a tournament ~2 MB), so every list view reads
 * this shape instead — see `listMatchSummaries` in lib/store.ts.
 */
export interface MatchSummary extends Omit<Match, 'files'> {
  fileCount: number;
}

/**
 * Admin-assigned ladder ranks for the Player Manager, keyed
 * `mode -> sub-mode -> normalized username -> rank`. Ranks are per
 * gamemode *and* sub-mode (NGMC Normal, NGMC Random, Erumode Balanced, ...)
 * because that is the granularity teams are autodrafted at — a player can
 * legitimately hold a different rank in each.
 */
export type SetRanks = Record<string, Record<string, Record<string, number>>>;

/**
 * The one stored decision about a username's identity, keyed by normalized
 * username like stats and Set Ranks. Global (one row per username across every
 * gamemode, unlike Set Ranks): a bot is a bot everywhere.
 *
 *   Bot     — force the bot badge on.
 *   NotBot  — force it off, overriding the automatic "username contains Bot"
 *             rule. This is the false-alarm escape hatch (RobotFan, Botanist).
 *
 * A *missing* row means "no decision", and the name rule then decides — which
 * is why ordinary players never need a row at all. See lib/player-tags.ts for
 * the rule and `resolvePlayerTag`, the only thing any view should call.
 */
export type PlayerTag = 'Bot' | 'NotBot';

// Payload shape used when creating/updating a match from the admin panel.
// The stats opt-out flag is deliberately NOT part of the editor payload —
// exclusion is a Tour Manager row action (see components/ExcludeStatsToggle),
// so updateMatch keeps the stored flag when the input leaves it undefined
// (the optional field below only exists so createMatch can set the initial
// value explicitly).
export interface MatchInput {
  name: string;
  date: string;
  region: Region;
  mode: Mode;
  submode: Submode;
  teams: Team[];
  files: MatchFile[];
  renames: Record<string, string>;
  substitutes?: Record<string, string>;
  playerRanks: Record<string, number>;
  excludeFromStats?: boolean;
}

export interface AttackRecord {
  title: string;
  artist: string;
  vn: string;
  playedAt: string | null;
  teams: string[]; // opposing team labels this attack hit
  effective: boolean;
}

export interface PlayerStats {
  uname: string;
  correct: number;
  taken: number;
  blocked: number;
  effTaken: number;
  effBlocked: number;
  attacks: AttackRecord[];
}

export interface TeamStats {
  teamIndex: number;
  label: string;
  members: PlayerStats[];
  present: string[]; // members who appear in at least one file
  missing: string[]; // members who never appear
  taken: number;
  blocked: number;
  effTaken: number;
  effBlocked: number;
}

export interface MatchStats {
  teams: TeamStats[];
  totalSongs: number;
}