"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VALID_TEAM_COUNTS = void 0;
exports.roundRobinCycles = roundRobinCycles;
exports.gamesPerTeam = gamesPerTeam;
exports.totalGamesExpected = totalGamesExpected;
exports.computeScheduleProgress = computeScheduleProgress;
exports.isValidTeamCount = isValidTeamCount;
exports.bracketSlot = bracketSlot;
exports.generateRoundRobin = generateRoundRobin;
exports.fileParticipantIndices = fileParticipantIndices;
exports.matchFilesToBracket = matchFilesToBracket;
const results_1 = require("./results");
const stats_1 = require("./stats");
// The only two valid tournament sizes. Cycle count is derived from team
// count, never chosen separately — 4 teams always double round robin
// (every pair plays twice, 6 games per team), 6 teams always single round
// robin (every pair plays once, 5 games per team).
exports.VALID_TEAM_COUNTS = [4, 6];
function roundRobinCycles(teamCount) {
    if (teamCount === 4)
        return 2;
    if (teamCount === 6)
        return 1;
    // Shouldn't happen if the 4/6 constraint is enforced at save time, but
    // fall back to single round robin rather than throwing mid-render.
    return 1;
}
function gamesPerTeam(teamCount) {
    return (teamCount - 1) * roundRobinCycles(teamCount);
}
function totalGamesExpected(teamCount) {
    return (teamCount * gamesPerTeam(teamCount)) / 2;
}
/**
 * Cross-references the expected round-robin fixture list (every pair,
 * `cycles` times) against however many games are actually recorded for
 * each pair, so the admin can see what's left to upload. Doesn't care
 * which specific two games satisfy a 2x pairing — just the count.
 */
function computeScheduleProgress(match) {
    const teams = match.teams;
    const n = teams.length;
    const cycles = roundRobinCycles(n);
    // Count recorded games per pair by scanning every scored file.
    const playedCount = new Map();
    for (const file of match.files) {
        const result = (0, results_1.computeGameResult)(file, teams);
        if (!result || result.entries.length !== 2)
            continue;
        const [i, j] = result.entries.map((e) => e.teamIndex).sort((a, b) => a - b);
        const key = `${i},${j}`;
        playedCount.set(key, (playedCount.get(key) ?? 0) + 1);
    }
    const pairs = [];
    for (let i = 0; i < n; i++) {
        for (let j = i + 1; j < n; j++) {
            const played = playedCount.get(`${i},${j}`) ?? 0;
            pairs.push({
                teamAIndex: i,
                teamBIndex: j,
                labelA: teams[i][0],
                labelB: teams[j][0],
                needed: cycles,
                played,
                remaining: Math.max(0, cycles - played),
            });
        }
    }
    const totalRecorded = pairs.reduce((s, p) => s + Math.min(p.played, p.needed), 0);
    const totalExpected = totalGamesExpected(n);
    return {
        cycles,
        gamesPerTeam: gamesPerTeam(n),
        totalExpected,
        totalRecorded,
        pairs,
        missingPairs: pairs.filter((p) => p.remaining > 0),
        complete: pairs.every((p) => p.remaining === 0),
    };
}
function isValidTeamCount(n) {
    return exports.VALID_TEAM_COUNTS.includes(n);
}
function bracketSlot(round, index) {
    return `r${round}m${index}`;
}
/**
 * One single round-robin pass using the circle method: team 0 is pinned
 * and the rest rotate, producing `n - 1` rounds of `n / 2` pairings.
 * Returns raw index pairs per round.
 */
function singleRoundRobinPairs(n) {
    const rot = [];
    for (let i = 1; i < n; i++)
        rot.push(i);
    const rounds = [];
    for (let r = 0; r < n - 1; r++) {
        const pairs = [[0, rot[rot.length - 1]]];
        for (let k = 0; k < (n - 2) / 2; k++) {
            pairs.push([rot[k], rot[rot.length - 2 - k]]);
        }
        rounds.push(pairs);
        rot.unshift(rot.pop()); // rotate clockwise
    }
    return rounds;
}
/**
 * Builds the full fixture bracket for a tournament: every round with its
 * matchups, autogenerated from the team list. 4 teams produce a double
 * round robin (2 cycles, 6 legs), 6 teams a single one (5 rounds). The
 * second cycle flips each pairing's side, and each of its legs is emitted
 * directly after the round it mirrors — R1, R1 (reverse), R2, R2
 * (reverse), ... — rather than appending the whole reversed cycle at the
 * end, so a round and its rematch read as one block.
 *
 * Every matchup carries a stable `slot` key so an uploaded JSON file (and
 * its scores) can be attached to a specific fixture. Slots keep the
 * cycle-major numbering they have always had (cycle * roundsPerCycle +
 * round); they are persisted on saved files, so they must not be
 * renumbered to follow the display order above.
 */
function generateRoundRobin(teams) {
    const n = teams.length;
    if (!isValidTeamCount(n))
        return [];
    const cycles = roundRobinCycles(n);
    const base = singleRoundRobinPairs(n);
    const roundsPerCycle = base.length;
    const rounds = [];
    for (let r = 0; r < roundsPerCycle; r++) {
        for (let c = 0; c < cycles; c++) {
            const matchups = base[r].map(([a, b], i) => {
                const [x, y] = c === 1 ? [b, a] : [a, b];
                return {
                    slot: bracketSlot(c * roundsPerCycle + r + 1, i),
                    round: r + 1,
                    cycle: c + 1,
                    teamAIndex: x,
                    teamBIndex: y,
                    labelA: teams[x][0],
                    labelB: teams[y][0],
                };
            });
            rounds.push({ round: r + 1, cycle: c + 1, matchups });
        }
    }
    return rounds;
}
/** Roster team indices whose players appear in a raw song-history file. */
function fileParticipantIndices(file, teams, renames = {}) {
    const normTeams = teams.map((t) => t.map(stats_1.norm));
    const present = new Set();
    for (const u of (0, stats_1.extractUsernames)(file.data)) {
        present.add((0, stats_1.norm)(renames[(0, stats_1.norm)(u)] || u));
    }
    const idx = [];
    normTeams.forEach((t, i) => {
        if (t.some((p) => present.has(p)))
            idx.push(i);
    });
    return idx;
}
/**
 * Binds uploaded files to bracket matchups. Files carrying an explicit
 * `slot` win outright; the rest are matched by the two teams detected in
 * them (first empty slot for that pair). Anything left over is returned
 * as `unmatched` so it isn't silently dropped.
 */
function matchFilesToBracket(teams, files, renames = {}) {
    const rounds = generateRoundRobin(teams);
    // Pair key -> slots in bracket order (2 for a double round robin).
    const slotsByPair = new Map();
    const allSlots = [];
    for (const rr of rounds) {
        for (const m of rr.matchups) {
            const key = `${Math.min(m.teamAIndex, m.teamBIndex)},${Math.max(m.teamAIndex, m.teamBIndex)}`;
            (slotsByPair.get(key) ?? slotsByPair.set(key, []).get(key)).push(m.slot);
            allSlots.push(m.slot);
        }
    }
    const bySlot = {};
    const used = new Set();
    const remaining = [];
    // Pass 1: explicit slots.
    for (const file of files) {
        if (file.slot && allSlots.includes(file.slot) && !bySlot[file.slot]) {
            bySlot[file.slot] = file;
            used.add(file.id);
        }
        else {
            remaining.push(file);
        }
    }
    // Pass 2: infer by the two teams present in each file.
    for (const file of remaining) {
        const idx = fileParticipantIndices(file, teams, renames);
        if (idx.length !== 2)
            continue;
        const key = `${Math.min(idx[0], idx[1])},${Math.max(idx[0], idx[1])}`;
        const slot = (slotsByPair.get(key) ?? []).find((s) => !bySlot[s]);
        if (slot) {
            bySlot[slot] = file;
            used.add(file.id);
        }
    }
    return { bySlot, unmatched: files.filter((f) => !used.has(f.id)) };
}
